### ISSUE TITLE
Kein Personal wechsel möglich

### ISSUE THREAD

**Issue by Europekicker** [delight-im/OpenSoccer#303]
Du musst also noch bis 23.01.1970 01:00 warten.

Du kannst jeden Assistenten nur alle 22 Tage austauschen. Du musst also noch bis 23.01.1970 01:00 warten.

**Comment by mwaclawek** [comment]
Thanks for your question!

The problem is definitely in `Website\ver_personal.php` or in the database table that is used.

In that file, there are three occurrences of your error message:
`addInfoBox(__('Du kannst jeden Assistenten nur alle`

Go to the place that handles your specific staff group, i.e. one of `jugendtrainer`, `fanbetreuer` and `scout`.

Then check why `mysql_affected_rows()` is `0` in that block and what value `$timeout` has.

**Comment by Europekicker** [comment]
$timeout = getTimestamp('-22 days');        think is ok
if (mysql_affected_rows() > 0)                    the same

Du musst also noch bis %s warten.', date('d.m.Y H:i', getTimestamp('+22 days', $ch3['zeit']))));

no problem in the php file

**Comment by mwaclawek** [comment]
You have to check the *values* of `$timeout` and `mysql_affected_rows()` at *runtime*, i.e. check what's number comes out when logging the value during execution.
