### ISSUE TITLE
data.sql UTF-8

### ISSUE THREAD

**Issue by bornhaeusser** [delight-im/OpenSoccer#328]
Short Question is the data.sql sett corect to utf8?
because the "Umalaute" are wrong (ä,ü,ö,etc)

**Comment by mwaclawek** [comment]
Well, it's certainly not the way the characters *should* be in the database, but it's what has always been working. So this has been kept around.

When it comes to UTF-8 storage and output:

 * The HTTP response headers from the website correctly declare UTF-8 as the charset.
 * The HTML meta tags do so as well.
 * All tables in the database are set to use UTF-8.

So there is no reason *not* to use UTF-8 everywhere, actually. But again, this is what has always been working.

If it doesn't work for you, maybe you have to adjust the charset for the database connection in `zzserver.php`, e.g. using:

```php
mysql_set_charset('latin1');
// or
mysql_set_charset('utf8');
```

Perhaps that helps. Otherwise, feel free to convert your database encoding (especially the encoding of the import files) as you like. Anyway, it's definitely possible to make the import work with the current setup and the import files as they are.
