### ISSUE TITLE
Pokal_Auslosen

### ISSUE THREAD

**Issue by bornhaeusser** [delight-im/OpenSoccer#330]
If running aa_pokal_auslosen.php the first time:

Notice: Undefined offset: 1 in /volume1/web/game/opensoccer/aa_pokal_auslosen.php on line 38 Notice: Undefined offset: 2 in /volume1/web/game/opensoccer/aa_pokal_auslosen.php on line 43 Notice: Undefined offset: 2 in /volume1/web/game/opensoccer/aa_pokal_auslosen.php on line 43 Notice: Undefined index: 8e296a067a37563370ded05f5a3bf3ec in /volume1/web/game/opensoccer/aa_pokal_auslosen.php on line 43

then i look in:

https://github.com/delight-im/OpenSoccer/issues/327

and have empty fields on same games.

**Comment by mwaclawek** [comment]
Thanks!

This is indeed the root cause of your problem. The `aa_pokal_auslosen.php` job looks at the `vorjahr_platz` column of the `teams` table to find the best teams of the previous season. These are the teams that qualify for the international cup. You know, just like it is in reality.

But for some leagues, that job does not find enough teams. So something has been wrong in the database. You might check the results of the SQL statement in line 29 of `aa_pokal_auslosen.php`.

If you've solved this problem, you can probably forget about https://github.com/delight-im/OpenSoccer/issues/327
